// <auto-generated />
namespace SloVVo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SpecifyingcolumnnamesforUserBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpecifyingcolumnnamesforUserBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202107251600155_Specifying column names for UserBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
