// <auto-generated />
namespace SloVVo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBorrowIdtouserbookprimarykey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBorrowIdtouserbookprimarykey));
        
        string IMigrationMetadata.Id
        {
            get { return "202110142011553_Add BorrowId to userbook primary key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
